### ISSUE TITLE
Extension failing to activate in Visual Studio code insiders and stable build

### ISSUE THREAD

**Issue by mmcintyre123** [LordBrom/HighlightDuplicates-vscode#4]
Suddenly today when I tried to toggle duplicate highlighting (command highlight-duplicates.toggleHighlightDuplicates), I get the following error message: 

![Image](https://github.com/user-attachments/assets/84e3e209-3e80-42b6-9957-b08df414f940)

Text:

> [Window Title]
> Visual Studio Code - Insiders
> 
> [Main Instruction]
> Command 'Highlight Duplicates: Toggle Highlighting' resulted in an error
> 
> [Content]
> command 'highlight-duplicates.toggleHighlightDuplicates' not found

It fails in the stable release of vscode as well.  In both versions I see the following in the Extension Host output (I have redacted my home folder with an ellipsis):

```
2025-05-13 13:19:24.299 [error] Activating extension LordBrom.highlight-duplicates failed due to an error:
2025-05-13 13:19:24.299 [error] TypeError: l[h].toLocaleLowerCase is not a function
    at s (...\.vscode\extensions\lordbrom.highlight-duplicates-1.1.0\dist\extension.js:1:2042)
    at e.activate (...\.vscode\extensions\lordbrom.highlight-duplicates-1.1.0\dist\extension.js:1:336)
    at Function.kb (file:///.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:15268)
    at Function.jb (file:///.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:14975)
    at file:///.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:13133
    at Nb.n (file:///.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13382)
    at Nb.m (file:///.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13345)
    at Nb.l (file:///.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:12801)

```
**VS Code Insiders Build:**
Version: 1.101.0-insider (user setup)
Commit: 4b88fa7949c13eea3369e8a05042a03f2f9df8be
Date: 2025-05-13T08:27:11.057Z (8 hrs ago)
Electron: 35.2.2
ElectronBuildId: 11520120
Chromium: 134.0.6998.205
Node.js: 22.14.0
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26100

**VS Code Stable Build:**
Version: 1.100.1 (user setup)
Commit: 91fa95bccb027ece6a968589bb1d662fa9c8e170
Date: 2025-05-09T15:43:50.040Z (4 days ago)
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by LordBrom** [comment]
Hello, I am able to replicate this when I have something that is not a string in the "ignoreList" setting array. Can you share your settings for this extension? or at least confirm if that is the case?
I can look into adding a check to weed out non-string values if that is the case.

**Comment by LordBrom** [comment]
This should be resolved with the new version (1.1.1). Please feel free to create a new issue if it persists, or there are any other issues. Thanks.

**Comment by mmcintyre123** [comment]
Thanks so much!  I tested the new version, and unfortunately the error persists.  I have created a new issue as requested.
